### ISSUE TITLE
デスクトップアプリの操作について

### ISSUE THREAD

**Issue by btbf** [hackaru-app/hackaru-desktop#503]
素晴らしいツールの開発ありがとうございます。

以下Windows10 64bit版でのことです。
■要望
・アプリを起動すると何も表示されない
　→重複起動することがある
　→タスクトレイ入っており、PC初心者は起動しているかがわからない
　→タスクバーに表示したい

・デスクトップアプリからプロジェクトを追加したい

・任意のGoogleアカウントのカレンダーに作業時間を追加することは可能でしょうか？
　（現状だとHackaruカレンダーが追加される）
　
ご確認お願い致します。

**Comment by btbf** [comment]
・デスクトップ上で前面表示・最小化を切り替えたい
・アプリからも「同じタスクで開始」する機能が欲しい

**Comment by ktmouk** [comment]
> アプリを起動すると何も表示されない
> 重複起動することがある

こちら修正します 👍  

> タスクトレイ入っており、PC初心者は起動しているかがわからない
> タスクバーに表示したい

ここは難しい所ですが、タスクバーにアイコンが表示されていると

- 誤ってアプリを終了してしまう可能性がある。たとえば Alt + F4 連打でウィンドウを全部閉じようとした時など
- 常に表示されているとタスクバーのスペースを取って邪魔になる可能性がある

と想定していて、タスクトレイに表示させるようにしています。
「PC初心者は起動しているかがわからない」という所は仰る通りなので初回起動の表示の仕方を考えてみます

> デスクトップアプリからプロジェクトを追加したい

プロジェクトの作成は、計測に比べると頻繁に発生しないものと想定していて、
Web版にアクセスして頂いてプロジェクトを作成してもらう流れでもUX上は問題ないかと想定していました。
ですが、要望が多いようでしたら機能実装を追加したいと思っています。

> 任意のGoogleアカウントのカレンダーに作業時間を追加することは可能でしょうか？

現状はできません。

> デスクトップアプリで前面表示・最小化を切り替えたい

ありがとうございます。こちらは仮に実装された場合、どのような使い方を想定されていますか?

> アプリからも「同じタスクで開始」する機能が欲しい

同じタスクで開始するボタンは無いですが、「作業内容や備考など」をクリックすると
過去の計測履歴が表示され、クリックすれば同じ内容で計測できます。
こちらでも素早く計測ができるので、代用できるかと思いました。

<img width="150" alt="スクリーンショット 2021-01-21 22 39 29" src="https://user-images.githubusercontent.com/17381979/105358481-9190a880-5c39-11eb-8e0a-0754285616a4.png">

**Comment by btbf** [comment]
> デスクトップアプリで前面表示・最小化を切り替えたい
常に手前に表示させておくことで、タスクごとの計測を素早く切り替えたい。
（長くかかるタスクの場合は最小化してタスクトレイに格納する）

**Comment by ktmouk** [comment]
@btbf 
こちらお待たせしました！
v1.4.0で「タスクバーに表示したい」「デスクトップアプリで前面表示・最小化を切り替えたい」の改善を実施しました ✨
このIssueはクローズしますが、追加で要望がある場合は TwitterのDM かこの Issues でお知らせくださいませ。
