### ISSUE TITLE
Goolgeカレンダーの反映について

### ISSUE THREAD

**Issue by btbf** [hackaru-app/hackaru-desktop#504]
Hackaru上のカレンダーには直ぐに反映されるのですが、
Google連携したカレンダーはリアルタイムに反映されないのですが、どのタイミングで反映されますでしょうか？

**Comment by ktmouk** [comment]
Googleの方から定期的にHackaruのサーバへカレンダーデータを取得してくる方法で同期しているので、
タイミングはGoogle側次第になります。平均でいうと1日、最大2日程度のラグがあります。
