### ISSUE TITLE
Time Zone Not Included In The List

### ISSUE THREAD

**Issue by slavakurilyak** [hackaru-app/hackaru-desktop#518]
When I try to create a new account, I see the following error:

![screen 3](https://user-images.githubusercontent.com/6625584/106363680-dde58380-62de-11eb-96e9-2606bb95e118.jpg)

My timezone is Pacific Standard Time (PST).

**Comment by ktmouk** [comment]
Hello @slavakurilyak, thank you for reporting the issue!
This issue has been fixed by https://github.com/hackaru-app/hackaru-api/pull/811.

Would you please try signing up again?

**Comment by slavakurilyak** [comment]
Thanks, I'm in! 😎
