### ISSUE TITLE
Initial Login fails using `yarn dev`

### ISSUE THREAD

**Issue by pSub** [hackaru-app/hackaru-desktop#817]
I've setup a local instance of Hackaru, following the Readme in https://github.com/hackaru-app/hackaru. This instance works so far without any problems.

If I start up Hackaru Desktop using `yarn dev` the initial login fails. My browser opens http://localhost:3333 and presents my HTTP Status 400. I see the following in the server logs:

```
api_1      | Started GET "/oauth/authorize?response_type=code&redirect_uri=http:%2F%2F127.0.0.1:35359&scope=activities:read+activities:write+projects:read+projects:write+suggestions:read+user:read&state=[FILTERED]&code_challenge=[FILTERED]&code_challenge_method=[FILTERED]" for 172.19.0.1 at 2021-10-25 21:06:09 +0000
api_1      | Processing by OAuth::AuthorizationsController#new as JSON
api_1      |   Parameters: {"response_type"=>"code", "redirect_uri"=>"http://127.0.0.1:35359", "scope"=>"activities:read activities:write projects:read projects:write suggestions:read user:read", "state"=>"[FILTERED]", "code_challenge"=>"[FILTERED]", "code_challenge_method"=>"[FILTERED]"}
api_1      |   AuthToken Load (0.3ms)  SELECT "auth_tokens".* FROM "auth_tokens" WHERE "auth_tokens"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
api_1      |   ↳ app/models/auth_token.rb:18:in `fetch'
api_1      |   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
api_1      |   ↳ app/controllers/concerns/authenticatable.rb:27:in `authenticate_auth_token!'
api_1      | Completed 400 Bad Request in 238ms (Views: 0.1ms | ActiveRecord: 3.9ms | Allocations: 4029)
```
I also tried to use the respective URLs from hackaru.app (ie. https://app.hackaru.app and https://api.hackaru.app) but I am presented with HTTP 400 as well.

Do I miss some important configuration? I tried look into the release artifact for the values used in the releases, but the build process uses Github secrets and I could find the values in the binaries on the first glance.

**Comment by pSub** [comment]
I realized that I have to create an OAuth application, to be able to connect the desktop client to the api server. Now I have a working config for api.hackaru.app (setting the correct client_id, which is logged by the bundled app). However it still isn't working. I think there is something messed up on my api server.

I've created an OAuth application using `rails console` and 

```Doorkeeper::Application.create(name: "Desktop client", redirect_uri: "http://127.0.0.1", scopes: "activities:read activities:write projects:read projects:write suggestions:read user:read")```

However I don't know if the value for the `redirect_uri` is correct. The desktop client changes ports frequently. Using the resulting `uid` as the `client_id` in the desktop app I'm able to see the page that prompts me to accept of reject the authorization request.

Once I click _accept_ I'm redirected to a site saying `Close your browser to continue`. However the desktop client isn't authorized and I see 401 errors in the logs of the client and server.

server:
```
api_1      | Started POST "/oauth/token" for 172.19.0.1 at 2021-11-04 22:04:10 +0000
api_1      | Processing by Doorkeeper::TokensController#create as HTML
api_1      |   Parameters: {"grant_type"=>"authorization_code", "client_id"=>"[FILTERED]", "redirect_uri"=>"http://127.0.0.1:45929", "code"=>"[FILTERED]", "code_verifier"=>"[FILTERED]"}
api_1      |   Doorkeeper::AccessGrant Load (0.5ms)  SELECT "oauth_access_grants".* FROM "oauth_access_grants" WHERE "oauth_access_grants"."token" = $1 LIMIT $2  [["token", "…"], ["LIMIT", 1]]
api_1      |   Doorkeeper::Application Load (0.6ms)  SELECT "oauth_applications".* FROM "oauth_applications" WHERE "oauth_applications"."uid" = $1 LIMIT $2  [["uid", "…"], ["LIMIT", 1]]
api_1      | Completed 401 Unauthorized in 9ms (Views: 0.2ms | ActiveRecord: 1.1ms | Allocations: 1787)
```

desktop client:
```
[dev:main    ] Handling Authorization Request  URLSearchParams { 'code' => '…', 'state' => '…' } … … null
[dev:main    ] Checking to see if there is an authorization response to be delivered.
[dev:main    ] Request ended with an error  401
```

Do you have any ideas what could be wrong with my setup? Unfortunately I don't know much about OAuth nor Doorkeeper.

**Comment by pSub** [comment]
:tada: I was able to authenticate using the desktop application! While doing some further research I stumbled upon https://stackoverflow.com/questions/63057801/do-we-really-need-client-secret-to-get-access-token-on-pkce-flow. One answer suggests to set the `confidential` field of `Doorkeeper::Application` to `false`. This work for me, but I'am unsure about the consequences. Is this the correct setup?

**Comment by ktmouk** [comment]
Thank you for reporting this issue! 👍 

The setup you wrote is correct. `confidential: false` is needed.
hackaru-desktop uses PKCE flow because native-application cannot have client-secret safely.

I am sorry for late reply and incomplete README. 
I'll fix the README soon.

**Comment by ktmouk** [comment]
I have improved the README.

**Comment by pSub** [comment]
Thank you, this is great! :rocket:
